=== habitat-sh/habitat/components/sup/doc/http_gateway_census_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema for all the data the Habitat supervisor makes available at the /census HTTP API endpoint",
  "properties": {
    "census_groups": {
      "additionalProperties": {
        "description": "A census group, keyed by service group",
        "properties": {
          "changed_service_files": {
            "description": "The names of the service files that have changed",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "election_status": {
            "description": "The status of the current election, if any",
            "type": "string"
          },
          "leader_id": {
            "description": "The member ID of the election leader, if there is one",
            "type": [
              "string",
              "null"
            ]
          },
          "local_member_id": {
            "description": "The local member ID",
            "type": "string"
          },
          "population": {
            "additionalProperties": {
              "description": "The census member",
              "properties": {
                "alive": {
                  "description": "Whether the member is alive",
                  "type": "boolean"
                },
                "cfg": {
                  "additionalProperties": {
                    "type": [
                      "boolean",
                      "string",
                      "integer",
                      "array",
                      "object"
                    ]
                  },
                  "description": "The configuration this member is currently exporting",
                  "type": "object"
                },
                "confirmed": {
                  "description": "Whether this member is confirmed dead/unreachable, from a network perspective",
                  "type": "boolean"
                },
                "departed": {
                  "description": "Whether this member has been departed from the ring",
                  "type": "boolean"
                },
                "election_is_finished": {
                  "description": "Whether a leader election for this service has finished",
                  "type": "boolean"
                },
                "election_is_no_quorum": {
                  "description": "Whether there is quorum for a leader electio for this service",
                  "type": "boolean"
                },
                "election_is_running": {
                  "description": "Whether there is a leader election running for this service",
                  "type": "boolean"
                },
                "follower": {
                  "description": "Whether this member is a follower",
                  "type": "boolean"
                },
                "group": {
                  "description": "The group portion of a service's complete group name",
                  "type": "string"
                },
                "leader": {
                  "description": "Whether this member is a leader",
                  "type": "boolean"
                },
                "member_id": {
                  "description": "This member's ID",
                  "type": "string"
                },
                "org": {
                  "description": "The organization of a service group specification",
                  "type": [
                    "null",
                    "string"
                  ]
                },
                "package": {
                  "description": "The package identifier",
                  "type": "string"
                },
                "persistent": {
                  "description": "Is this member a permanent peer",
                  "type": "boolean"
                },
                "pkg": {
                  "$deprecated": "Since 0.66.0; please use 'package' instead.",
                  "$ref": "render_context_schema.json#/definitions/package_identifier"
                },
                "service": {
                  "description": "The name of the service",
                  "type": "string"
                },
                "suspect": {
                  "description": "Whether this member is considered possibly unreachable, from a network perspective",
                  "type": "boolean"
                },
                "sys": {
                  "$ref": "http_gateway_butterfly_schema.json#/definitions/sys_basic"
                },
                "update_election_is_finished": {
                  "description": "Whether the update leader election has finished",
                  "type": "boolean"
                },
                "update_election_is_no_quorum": {
                  "description": "Whether there is a quorum for an update leader election",
                  "type": "boolean"
                },
                "update_election_is_running": {
                  "description": "Whether an update leader election is running",
                  "type": "boolean"
                },
                "update_follower": {
                  "description": "Whether this member is an update follower",
                  "type": "boolean"
                },
                "update_leader": {
                  "description": "Whether this member is an update leader",
                  "type": "boolean"
                }
              },
              "type": "object"
            },
            "description": "The census population, keyed by member ID",
            "type": "object"
          },
          "service_config": {
            "description": "The service config for this member",
            "properties": {
              "incarnation": {
                "description": "The incarnation number for this config",
                "type": "integer"
              },
              "value": {
                "additionalProperties": {
                  "type": [
                    "boolean",
                    "string",
                    "integer",
                    "array",
                    "object"
                  ]
                },
                "description": "The config value",
                "type": "object"
              }
            },
            "required": [
              "incarnation",
              "value"
            ],
            "type": [
              "null",
              "object"
            ]
          },
          "service_files": {
            "additionalProperties": {
              "type": "object",
              "description": "Each file, keyed by file name",
              "properties": {
                "filename": {
                  "type": "string",
                  "description": "The name of the file"
                },
                "incarnation": {
                  "type": "integer",
                  "description": "The incarnation number of this file"
                },
                "body": {
                  "type": "array",
                  "description": "Each of the bytes in the file",
                  "$deprecated": "Since 0.66.0",
                  "items": {
                    "type": "integer"
                  }
                }
              }
            },
            "description": "The service files for this member",
            "type": [
              "null",
              "object"
            ]
          },
          "service_group": {
            "description": "The service group",
            "type": "string"
          },
          "update_election_status": {
            "description": "The status of an update election, if one is running",
            "type": "string"
          },
          "update_leader_id": {
            "description": "The member ID of the update leader, if present",
            "type": [
              "null",
              "string"
            ]
          }
        },
        "required": [
          "changed_service_files",
          "election_status",
          "leader_id",
          "local_member_id",
          "population",
          "service_config",
          "service_files",
          "service_group",
          "update_election_status",
          "update_leader_id"
        ],
        "type": "object"
      },
      "description": "A description of the various service groups present in the census",
      "type": "object"
    },
    "changed": {
      "$deprecated": "Since 0.66.0",
      "description": "Whether the census has changed",
      "type": "boolean"
    },
    "last_election_counter": {
      "$deprecated": "Since 0.66.0",
      "description": "The counter for the last time an election rumor was updated",
      "type": "integer"
    },
    "last_election_update_counter": {
      "$deprecated": "Since 0.66.0",
      "description": "The counter for the last time an election update rumor was updated",
      "type": "integer"
    },
    "last_membership_counter": {
      "$deprecated": "Since 0.66.0",
      "description": "The counter for the last time a membership rumor was updated",
      "type": "integer"
    },
    "last_service_config_counter": {
      "$deprecated": "Since 0.66.0",
      "description": "The counter for the last time a service config rumor was updated",
      "type": "integer"
    },
    "last_service_counter": {
      "$deprecated": "Since 0.66.0",
      "description": "The counter for thet last time a service rumor was updated",
      "type": "integer"
    },
    "last_service_file_counter": {
      "$deprecated": "Since 0.66.0",
      "description": "The counter for the last time a service file rumor was updated",
      "type": "integer"
    },
    "local_member_id": {
      "description": "The local member ID",
      "type": "string"
    }
  },
  "required": [
    "census_groups",
    "local_member_id"
  ],
  "type": "object"
}

=== habitat-sh/habitat/components/sup/tests/fixtures/http-gateway/sample-census-output.json
{
  "census_groups": {
    "builder-api-proxy.default": {
      "changed_service_files": [],
      "election_status": "None",
      "leader_id": null,
      "local_member_id": "1154ec64a1714cdca5c885a181e41737",
      "population": {
        "0d262679fc604664825ad916de6a399c": {
          "alive": true,
          "application": null,
          "cfg": {
            "port": 80,
            "ssl-port": 443,
            "url": "https://bldr.habitat.sh"
          },
          "confirmed": false,
          "departed": false,
          "election_is_finished": false,
          "election_is_no_quorum": false,
          "election_is_running": false,
          "environment": null,
          "follower": false,
          "group": "default",
          "leader": false,
          "member_id": "0d262679fc604664825ad916de6a399c",
          "org": null,
          "persistent": true,
          "pkg": {
            "name": "builder-api-proxy",
            "origin": "habitat",
            "release": "20180828215018",
            "version": "7590"
          },
          "service": "builder-api-proxy",
          "suspect": false,
          "sys": {
            "ctl_gateway_ip": "0.0.0.0",
            "ctl_gateway_port": 9632,
            "gossip_ip": "172.26.0.9",
            "gossip_port": 9638,
            "hostname": "api-proxy.habitat.dev",
            "http_gateway_ip": "0.0.0.0",
            "http_gateway_port": 9631,
            "ip": "172.25.0.6"
          },
          "update_election_is_finished": false,
          "update_election_is_no_quorum": false,
          "update_election_is_running": false,
          "update_follower": false,
          "update_leader": false
        }
      },
      "service_config": null,
      "service_files": {},
      "service_group": "builder-api-proxy.default",
      "update_election_status": "None",
      "update_leader_id": null
    },
    "builder-api.default": {
      "changed_service_files": [],
      "election_status": "None",
      "leader_id": null,
      "local_member_id": "1154ec64a1714cdca5c885a181e41737",
      "population": {
        "be57ce74c75d4b29a4d8602c28397364": {
          "alive": true,
          "application": null,
          "cfg": {
            "port": 9636
          },
          "confirmed": false,
          "departed": false,
          "election_is_finished": false,
          "election_is_no_quorum": false,
          "election_is_running": false,
          "environment": null,
          "follower": false,
          "group": "default",
          "leader": false,
          "member_id": "be57ce74c75d4b29a4d8602c28397364",
          "org": null,
          "persistent": true,
          "pkg": {
            "name": "builder-api",
            "origin": "habitat",
            "release": "20180906202535",
            "version": "7602"
          },
          "service": "builder-api",
          "suspect": false,
          "sys": {
            "ctl_gateway_ip": "0.0.0.0",
            "ctl_gateway_port": 9632,
            "gossip_ip": "172.26.0.8",
            "gossip_port": 9638,
            "hostname": "api.habitat.dev",
            "http_gateway_ip": "0.0.0.0",
            "http_gateway_port": 9631,
            "ip": "172.26.0.8"
          },
          "update_election_is_finished": false,
          "update_election_is_no_quorum": false,
          "update_election_is_running": false,
          "update_follower": false,
          "update_leader": false
        }
      },
      "service_config": {
        "incarnation": 1534943508,
        "value": {
          "api": {
            "features_enabled": "jobsrv"
          },
          "depot": {
            "builds_enabled": true
          },
          "github": {
            "app_id": 123456,
            "client_id": "hahano",
            "client_secret": "justkidding",
            "enabled": true,
            "redirect_url": "https://bldr.habitat.sh/",
            "webhook_secret": "nowayjose"
          },
          "log_level": "info",
          "oauth": {
            "client_id": "fakeclientidyo",
            "client_secret": "topsekret",
            "provider": "github",
            "redirect_url": "https://bldr.habitat.sh/",
            "token_url": "https://github.com/login/oauth/access_token",
            "userinfo_url": "https://api.github.com/user"
          },
          "s3": {
            "backend": "aws",
            "bucket_name": "habitat-builder-artifact-store.live",
            "endpoint": "us-west-2",
            "key_id": "justkidding",
            "secret_key": "password123"
          },
          "segment": {
            "write_key": "goodtimes"
          }
        }
      },
      "service_files": {
        "bldr-20170927023714.box.key": {
          "body": [
            66,
            61
          ],
          "filename": "bldr-20170927023714.box.key",
          "incarnation": 1534943508
        },
        "bldr-20170927023714.pub": {
          "body": [
            66,
            61
          ],
          "filename": "bldr-20170927023714.pub",
          "incarnation": 1534943508
        },
        "builder-github-app.pem": {
          "body": [
            45,
            10
          ],
          "filename": "builder-github-app.pem",
          "incarnation": 1534943508
        }
      },
      "service_group": "builder-api.default",
      "update_election_status": "None",
      "update_leader_id": null
    },
    "builder-datastore.default": {
      "changed_service_files": [],
      "election_status": "None",
      "leader_id": null,
      "local_member_id": "1154ec64a1714cdca5c885a181e41737",
      "population": {
        "b2c535a80ba5463a8e43672801fd803b": {
          "alive": true,
          "application": null,
          "cfg": {
            "port": 5432
          },
          "confirmed": false,
          "departed": false,
          "election_is_finished": false,
          "election_is_no_quorum": false,
          "election_is_running": false,
          "environment": null,
          "follower": false,
          "group": "default",
          "leader": false,
          "member_id": "b2c535a80ba5463a8e43672801fd803b",
          "org": null,
          "persistent": true,
          "pkg": {
            "name": "builder-datastore",
            "origin": "habitat",
            "release": "20180828215240",
            "version": "7590"
          },
          "service": "builder-datastore",
          "suspect": false,
          "sys": {
            "ctl_gateway_ip": "0.0.0.0",
            "ctl_gateway_port": 9632,
            "gossip_ip": "172.26.0.3",
            "gossip_port": 9638,
            "hostname": "datastore.habitat.dev",
            "http_gateway_ip": "0.0.0.0",
            "http_gateway_port": 9631,
            "ip": "172.25.0.4"
          },
          "update_election_is_finished": false,
          "update_election_is_no_quorum": false,
          "update_election_is_running": false,
          "update_follower": false,
          "update_leader": false
        }
      },
      "service_config": null,
      "service_files": {},
      "service_group": "builder-datastore.default",
      "update_election_status": "None",
      "update_leader_id": null
    },
    "builder-jobsrv.default": {
      "changed_service_files": [],
      "election_status": "None",
      "leader_id": null,
      "local_member_id": "1154ec64a1714cdca5c885a181e41737",
      "population": {
        "c2ca91559a1f4114a819a1ca283cf10a": {
          "alive": true,
          "application": null,
          "cfg": {
            "log_port": 5568,
            "worker_heartbeat": 5567,
            "worker_port": 5566
          },
          "confirmed": false,
          "departed": false,
          "election_is_finished": false,
          "election_is_no_quorum": false,
          "election_is_running": false,
          "environment": null,
          "follower": false,
          "group": "default",
          "leader": false,
          "member_id": "c2ca91559a1f4114a819a1ca283cf10a",
          "org": null,
          "persistent": true,
          "pkg": {
            "name": "builder-jobsrv",
            "origin": "habitat",
            "release": "20180906201133",
            "version": "7602"
          },
          "service": "builder-jobsrv",
          "suspect": false,
          "sys": {
            "ctl_gateway_ip": "0.0.0.0",
            "ctl_gateway_port": 9632,
            "gossip_ip": "172.26.0.7",
            "gossip_port": 9638,
            "hostname": "jobsrv.habitat.dev",
            "http_gateway_ip": "0.0.0.0",
            "http_gateway_port": 9631,
            "ip": "172.25.0.9"
          },
          "update_election_is_finished": false,
          "update_election_is_no_quorum": false,
          "update_election_is_running": false,
          "update_follower": false,
          "update_leader": false
        }
      },
      "service_config": null,
      "service_files": {},
      "service_group": "builder-jobsrv.default",
      "update_election_status": "None",
      "update_leader_id": null
    },
    "builder-minio.default": {
      "changed_service_files": [],
      "election_status": "None",
      "leader_id": null,
      "local_member_id": "1154ec64a1714cdca5c885a181e41737",
      "population": {
        "f723be0d353e45c7bfa097aa586b8795": {
          "alive": true,
          "application": null,
          "cfg": {},
          "confirmed": false,
          "departed": false,
          "election_is_finished": false,
          "election_is_no_quorum": false,
          "election_is_running": false,
          "environment": null,
          "follower": false,
          "group": "default",
          "leader": false,
          "member_id": "f723be0d353e45c7bfa097aa586b8795",
          "org": null,
          "persistent": true,
          "pkg": {
            "name": "builder-minio",
            "origin": "habitat",
            "release": "20180828222034",
            "version": "0.1.0"
          },
